require 'test/unit'
require 'rubygems'
require 'active_support'
require 'active_support/test_case'
require 'active_record'
require 'active_record/test_case'
require File.dirname(__FILE__) + '/../lib/foreigner'